"""Copy for the isolated browser component; no market-feed or book dependency."""
LAB_COPY = {
    'title': ('Interactive Greeks Lab', 'Laboratoire interactif des Greeks'),
    'intro': ('One European option. Six assumptions. Twenty views of local risk.',
              'Une option européenne. Six hypothèses. Vingt vues du risque local.'),
    'source': ('USER INPUT · BSM MODEL · PER UNDERLYING UNIT', 'SAISIE UTILISATEUR · MODÈLE BSM · PAR UNITÉ DE SOUS-JACENT'),
    'origin': ('Inputs start from an illustrative scenario, independent of the book and market feed. Nothing is fetched or refreshed automatically. Only your inputs change these theoretical values.',
               'Les paramètres démarrent sur un scénario illustratif, indépendant du portefeuille et des données de marché. Aucun flux ni rafraîchissement automatique : seules vos saisies changent ces valeurs théoriques.'),
    'S': ('Spot S', 'Spot S'), 'K': ('Strike K', 'Strike K'),
    'T': ('Expiry T · years', 'Échéance T · années'),
    'sigma': ('Volatility σ · %', 'Volatilité σ · %'),
    'r': ('Risk-free rate r · %', 'Taux sans risque r · %'),
    'q': ('Dividend yield q · %', 'Rendement dividende q · %'),
    'number': ('numeric input', 'saisie numérique'), 'slider': ('slider', 'curseur'),
    'reset': ('Reset defaults', 'Rétablir les valeurs'), 'fit': ('Fit chart axes', 'Ajuster les axes'),
    'invalid': ('Enter a number within the displayed bounds; charts retain the last valid value.',
                'Saisissez un nombre dans les bornes indiquées ; les graphiques conservent la dernière valeur valide.'),
    'call': ('Call · right to buy', 'Call · droit d’acheter'),
    'put': ('Put · right to sell', 'Put · droit de vendre'),
    'call_value': ('Call value', 'Valeur du call'), 'put_value': ('Put value', 'Valeur du put'),
    'value_unit': ('Currency units / underlying unit', 'Unités de devise / unité de sous-jacent'),
    'distribution': ('N = standard normal CDF · φ = standard normal density',
                     'N = fonction de répartition normale · φ = densité normale'),
    'first': ('01 / Value → first-order sensitivity', '01 / Valeur → sensibilité de premier ordre'),
    'second': ('02 / Sensitivity → second-order & cross Greeks', '02 / Sensibilité → Greeks de second ordre et croisés'),
    'curve': ('Analytical curve', 'Courbe analytique'), 'tangent': ('Local tangent', 'Tangente locale'),
    'point': ('Current scenario', 'Scénario courant'),
    'slope': ('Tangent slope', 'Pente de la tangente'),
    'price': ('Option value', 'Valeur de l’option'), 'delta': ('Delta', 'Delta'), 'vega': ('Vega · raw', 'Vega · brute'),
    'axis_S': ('Spot S', 'Spot S'), 'axis_K': ('Strike K', 'Strike K'),
    'axis_T': ('Remaining T · years', 'T restant · années'),
    'axis_sigma': ('σ · decimal (0.25 = 25%)', 'σ · décimal (0,25 = 25 %)'),
    'axis_r': ('r · decimal (0.03 = 3%)', 'r · décimal (0,03 = 3 %)'),
    'axes': ('Axes hold steady as you drag; they expand only if the current point leaves the view. Curves are fitted on release if needed. Fit chart axes recentres every view.',
             'Les axes restent fixes pendant le déplacement ; ils s’élargissent si le point sort du cadre. Les courbes sont ajustées au relâchement si nécessaire. Ajuster les axes recentre chaque vue.'),
    'clipped': ('Curve extends beyond the view · fit axes', 'Courbe hors du cadre · ajuster les axes'),
    'help': ('Read the graphs & understand the units', 'Lire les graphiques et comprendre les unités'),
    'read': ('Each chart changes only its horizontal-axis variable, holding the other five inputs fixed. The point is your scenario; the dashed line is its local tangent, not a forecast. Identical call/put Gamma and Vega are a property of BSM.',
             'Chaque graphique fait varier uniquement sa variable horizontale ; les cinq autres paramètres restent fixes. Le point représente votre scénario et les tirets sa tangente locale, pas une prévision. Les Gamma et Vega identiques du call et du put sont une propriété de BSM.'),
    'units': ('Chart slopes use raw derivatives: σ and r are decimals, T is in years, values in currency units. A 1 vol point move is 0.01; a 1 bp rate move is 0.0001. The market-unit equivalents below do not rescale chart tangents.',
              'Les pentes sont des dérivées brutes : σ et r en décimal, T en années, valeurs en unités de devise. Un point de vol vaut 0,01 ; un point de base de taux vaut 0,0001. Les équivalents de marché ci-dessous ne modifient pas les tangentes.'),
    'time': ('Time convention: Theta, Charm and Veta measure elapsed time t. Since remaining T falls as t rises, their T-chart slopes are −Theta, −Charm and −Veta. Both the Greek and actual slope are shown.',
             'Convention de temps : Theta, Charm et Veta mesurent le temps écoulé t. Le temps restant T diminuant lorsque t augmente, les pentes en T sont −Theta, −Charm et −Veta. Le Greek et la pente réelle sont affichés.'),
    'assumptions': ('European exercise; constant volatility, continuously compounded r and dividend yield q; no fees, discrete dividends or bid/ask. These are model values, not executable quotes. Float underflow can make extremely small tails zero.',
                    'Exercice européen ; volatilité constante, taux r et dividendes q continus ; sans frais, dividendes discrets ni fourchette achat/vente. Valeurs de modèle, pas des prix exécutables. Les probabilités extrêmement faibles peuvent être arrondies à zéro par le calcul numérique.'),
    'market': ('Market-unit equivalents', 'Équivalents en unités de marché'),
    'per_vol': ('Vega / 1 vol point', 'Vega / 1 point de vol'), 'per_bp': ('Rho / 1 bp', 'Rho / 1 pb'),
    'per_day': ('Theta / calendar day (365)', 'Theta / jour calendaire (365)'),
    'live': ('Local calculations · live input', 'Calculs locaux · saisie en continu'),
    'help_delta': ('∂V/∂S · value change per spot unit; all other inputs fixed.', '∂V/∂S · variation de valeur par unité de spot ; autres paramètres fixes.'),
    'help_dual_delta': ('∂V/∂K · value change per strike unit, holding spot fixed.', '∂V/∂K · variation de valeur par unité de strike, spot fixe.'),
    'help_gamma': ('∂Delta/∂S · Delta change per spot unit; curvature of option value.', '∂Delta/∂S · variation du Delta par unité de spot ; courbure de la valeur.'),
    'help_vega': ('∂V/∂σ · value sensitivity to decimal volatility. Multiply by 0.01 for one vol point.', '∂V/∂σ · sensibilité à la volatilité décimale. Multiplier par 0,01 pour un point de vol.'),
    'help_theta': ('∂V/∂t = −∂V/∂T · value change per elapsed year; divide by 365 for a calendar day.', '∂V/∂t = −∂V/∂T · variation de valeur par année écoulée ; diviser par 365 pour un jour calendaire.'),
    'help_rho': ('∂V/∂r · value sensitivity to the decimal rate. Multiply by 0.0001 for one basis point.', '∂V/∂r · sensibilité au taux décimal. Multiplier par 0,0001 pour un point de base.'),
    'help_vanna': ('∂Delta/∂σ = ∂Vega/∂S · Delta change per decimal volatility unit.', '∂Delta/∂σ = ∂Vega/∂S · variation du Delta par unité de volatilité décimale.'),
    'help_charm': ('∂Delta/∂t = −∂Delta/∂T · Delta change per elapsed year, spot and volatility fixed.', '∂Delta/∂t = −∂Delta/∂T · variation du Delta par année écoulée, spot et volatilité fixes.'),
    'help_vomma': ('∂Vega/∂σ · raw Vega change per decimal volatility unit; also called Volga.', '∂Vega/∂σ · variation du Vega brut par unité de volatilité décimale ; aussi appelé Volga.'),
    'help_veta': ('∂Vega/∂t = −∂Vega/∂T · raw Vega change per elapsed year.', '∂Vega/∂t = −∂Vega/∂T · variation du Vega brut par année écoulée.'),
}


def lab_copy(language):
    return {key: pair[language == 'fr'] for key, pair in LAB_COPY.items()}
