"""Bilingual copy for the introductory menu; no market or model calculations."""

WELCOME = {
    'nav.welcome': ('Start', 'Accueil'),
    'welcome.status': ('GETTING STARTED · EXPLAINED STEP BY STEP', 'DÉCOUVERTE · EXPLIQUÉ PAS À PAS'),
    'welcome.kicker': ('YOUR GUIDE TO THE TERMINAL', 'VOTRE GUIDE DU TERMINAL'),
    'welcome.title': ('From markets to your portfolio. Make the connections.', 'Des marchés au portefeuille. Faites le lien.'),
    'welcome.intro': ('Explore markets, understand a portfolio’s risks and test what could happen. Five workspaces connect to one shared portfolio, with explanations at every step.', 'Explorez les marchés, comprenez les risques d’un portefeuille et testez ce qui pourrait se passer. Cinq espaces sont reliés à un même portefeuille, avec des explications à chaque étape.'),
    'welcome.start': ('Open the overview →', 'Ouvrir la vue d’ensemble →'),
    'welcome.ready': ('A demo portfolio is ready. You can explore without importing anything.', 'Un portefeuille de démonstration est prêt. Vous pouvez explorer sans rien importer.'),
    'welcome.current': ('Current portfolio', 'Portefeuille actuel'),
    'welcome.positions': ('{count} positions · values in {currency}', '{count} positions · valeurs en {currency}'),
    'welcome.keep': ('Opening a workspace keeps your current portfolio. Change the demo or edit positions once inside.', 'Ouvrir un espace conserve votre portefeuille actuel. Vous pourrez changer de démo ou modifier les positions dans le terminal.'),
    'welcome.route': ('A simple first visit', 'Un premier parcours tout simple'),
    'welcome.step1.title': ('Take in the big picture', 'Commencez par la vue d’ensemble'),
    'welcome.step1.body': ('See the portfolio’s value, its main exposures and what drives its risk.', 'Repérez la valeur du portefeuille, ses principales expositions et ce qui contribue au risque.'),
    'welcome.step2.title': ('Ask “what if?”', 'Posez la question « et si ? »'),
    'welcome.step2.body': ('In Risk Lab, test a rise in rates or a fall in equities. Compare the hypothetical impact.', 'Dans le laboratoire de risque, testez une hausse des taux ou une baisse des actions. Comparez l’impact hypothétique.'),
    'welcome.step3.title': ('Understand the result', 'Comprenez le résultat'),
    'welcome.step3.body': ('Use the metric help icons and each workspace’s guide to check meanings, sources and assumptions.', 'Utilisez les icônes d’aide et le guide de chaque espace pour comprendre les indicateurs, les sources et les hypothèses.'),
    'welcome.menu': ('What would you like to explore?', 'Que souhaitez-vous explorer ?'),
    'welcome.menu_hint': ('Start with the overview, or go straight to a question. Your portfolio connects all five spaces.', 'Commencez par la vue d’ensemble, ou choisissez directement une question. Votre portefeuille relie les cinq espaces.'),
    'welcome.overview.title': ('The big picture', 'La vue d’ensemble'),
    'welcome.overview.question': ('Where does my portfolio stand?', 'Où en est mon portefeuille ?'),
    'welcome.overview.body': ('Its value, main risks and hypothetical stress losses, together on one screen.', 'Sa valeur, ses principaux risques et les pertes dans différents scénarios hypothétiques, réunis sur un écran.'),
    'welcome.overview.open': ('See the portfolio →', 'Voir le portefeuille →'),
    'welcome.markets.title': ('Markets', 'Les marchés'),
    'welcome.markets.question': ('What do rates and currencies tell me?', 'Que montrent les taux et les devises ?'),
    'welcome.markets.body': ('Read dated yield curves and exchange rates. Explore bond sensitivity and currency hedges.', 'Lisez les courbes de taux et les cours de change datés. Explorez la sensibilité des obligations et les couvertures de change.'),
    'welcome.markets.open': ('Explore markets →', 'Explorer les marchés →'),
    'welcome.risk.title': ('Portfolio risk', 'Le risque du portefeuille'),
    'welcome.risk.question': ('What could make my portfolio lose value?', 'Qu’est-ce qui pourrait faire baisser sa valeur ?'),
    'welcome.risk.body': ('Edit positions, identify risk contributions and compare the effects of hypothetical shocks.', 'Modifiez les positions, identifiez les contributions au risque et comparez l’effet de chocs hypothétiques.'),
    'welcome.risk.open': ('Test the risks →', 'Tester les risques →'),
    'welcome.derivatives.title': ('Options & structured notes', 'Options & produits structurés'),
    'welcome.derivatives.question': ('How does a contract react to the market?', 'Comment un contrat réagit-il au marché ?'),
    'welcome.derivatives.body': ('Explore option strategies, barriers and Discount/Bonus certificates in the Product workshop, alongside book options and structured notes.', 'Explorez stratégies d’options, barrières et certificats Discount/Bonus dans l’Atelier produits, en complément des options et produits structurés du portefeuille.'),
    'welcome.derivatives.open': ('Understand derivatives →', 'Comprendre les dérivés →'),
    'welcome.financing.title': ('Financing & collateral', 'Financement & garanties'),
    'welcome.financing.question': ('How much cash and collateral are needed?', 'Quels besoins en cash et en garanties ?'),
    'welcome.financing.body': ('Understand borrowing against securities, lending income and margin calls. Separate costs from liquidity needs.', 'Comprenez l’emprunt garanti par des titres, les revenus de prêt et les appels de marge. Distinguez les coûts des besoins de liquidité.'),
    'welcome.financing.open': ('Explore financing →', 'Explorer le financement →'),
    'welcome.faq': ('A few things to know', 'Quelques repères avant de commencer'),
    'welcome.faq.data.title': ('Where do the numbers come from? Are they live?', 'D’où viennent les chiffres ? Sont-ils en direct ?'),
    'welcome.faq.data.body': ('Market context combines public observations (Yahoo Finance, FRED and the ECB when available) with clearly labelled demo fallbacks. Dates and providers appear in the workspace guides. Data loads when you enter a workspace; Markets offers a refresh action with a 15-minute cache. This is not a streaming feed.', 'Le contexte de marché combine des observations publiques (Yahoo Finance, FRED et BCE lorsqu’elles sont disponibles) avec des données de démonstration clairement identifiées en cas de repli. Les dates et fournisseurs figurent dans les guides. Les données se chargent à l’entrée dans un espace ; Marchés propose une actualisation avec un cache de 15 minutes. Ce n’est pas un flux en direct.'),
    'welcome.faq.book.title': ('What is a “book”? Is this a real account?', 'Qu’est-ce qu’un « book » ? Est-ce un vrai compte ?'),
    'welcome.faq.book.body': ('A book is simply a portfolio: a list of assets and quantities held or sold short. The terminal starts with a demonstration portfolio; it is not connected to a brokerage account and places no real orders. Edits are kept during the current session. A full browser reload can reset the demo.', 'Un « book » est simplement un portefeuille : une liste d’actifs et de quantités détenues ou vendues à découvert. Le terminal démarre avec une démonstration ; il n’est pas relié à un compte de courtage et ne passe aucun ordre réel. Les modifications sont conservées pendant la session. Un rechargement complet du navigateur peut réinitialiser la démo.'),
    'welcome.faq.controls.title': ('What changes when I move a control?', 'Qu’est-ce qui change quand je modifie un réglage ?'),
    'welcome.faq.controls.body': ('Applied positions, contract terms and shared market inputs affect the same portfolio across workspaces. A local scenario, curve or simulation is a what-if view; it does not book a trade. Each workspace explains which controls are shared. Changing pages, language or appearance does not reset your positions.', 'Les positions appliquées, les conditions des contrats et les paramètres de marché partagés affectent le même portefeuille dans les différents espaces. Un scénario, une courbe ou une simulation locale sert à explorer une hypothèse ; cela n’ajoute pas de transaction. Chaque guide indique les réglages partagés. Changer de page, de langue ou d’apparence ne réinitialise pas vos positions.'),
    'welcome.faq.metrics.title': ('How should I read the indicators and simulations?', 'Comment lire les indicateurs et les simulations ?'),
    'welcome.faq.metrics.body': ('NAV is the portfolio’s net value; P&L is its gain or loss. VaR and Expected Shortfall describe losses within the selected risk model, not a guaranteed maximum. The risk history and volatility surfaces are synthetic, and scenarios are hypothetical rather than forecasts. Use the help icons for units and the expandable methodology for assumptions.', 'La VL est la valeur nette du portefeuille ; le P&L est son gain ou sa perte. La VaR et la perte moyenne extrême décrivent les pertes selon le modèle de risque choisi, pas un maximum garanti. L’historique de risque et les surfaces de volatilité sont synthétiques ; les scénarios sont des hypothèses, pas des prévisions. Les icônes d’aide précisent les unités et les volets de méthodologie détaillent les hypothèses.'),
}
