"""Bilingual explanations for standalone derivative product experiments."""
WORKSHOP = {
 'workshop': ('Product workshop', 'Atelier produits'),
 'workshop.intro': ('Build a payoff. Understand what you own.', 'Construire un payoff. Comprendre ce que l’on détient.'),
 'workshop.source': ('USER INPUT · Independent examples start at spot 100. All prices here come from the formulas and parameters below, not live quotes. These experiments do not change your portfolio or its risk reports.', 'SAISIE UTILISATEUR · Exemples indépendants avec un spot initial de 100. Les prix proviennent des formules et des paramètres ci-dessous, pas de cotations en direct. Ces simulations ne modifient ni le portefeuille ni ses rapports de risque.'),
 'workshop.choose': ('Choose an experiment', 'Choisir une expérience'),
 'workshop.strategies': ('Option strategies', 'Stratégies d’options'),
 'workshop.barriers': ('Barrier options', 'Options à barrière'),
 'workshop.certificates': ('Discount & Bonus certificates', 'Certificats Discount et Bonus'),
 'workshop.inputs': ('Model inputs', 'Paramètres du modèle'),
 'workshop.spot': ('Underlying price · S', 'Cours du sous-jacent · S'),
 'workshop.strike': ('Strike · K', 'Prix d’exercice · K'),
 'workshop.second_strike': ('Second strike · K₂', 'Second prix d’exercice · K₂'),
 'workshop.dividend': ('Continuous dividend yield (%)', 'Rendement continu des dividendes (%)'),
 'workshop.parameters': ('S is the underlying price today; K is the exercise price; T is the remaining time in years. Volatility is the annual size of fluctuations, not an expected return. The rate and dividend yield use continuous compounding.', 'S est le cours du sous-jacent aujourd’hui ; K est le prix d’exercice ; T est le temps restant en années. La volatilité mesure l’ampleur annuelle des fluctuations, pas un rendement attendu. Le taux et les dividendes sont exprimés en capitalisation continue.'),
 'workshop.unit': ('All amounts are in the same chosen currency, per underlying unit; no automatic ×100 contract multiplier.', 'Tous les montants sont dans une même devise choisie, par unité de sous-jacent ; aucun multiplicateur de contrat ×100 automatique.'),
 'workshop.price': ('Model value / unit', 'Valeur modèle / unité'),
 'workshop.vanilla_value': ('Vanilla value / unit', 'Valeur vanille / unité'),
 'workshop.terminal': ('Underlying price at expiry', 'Cours du sous-jacent à l’échéance'),
 'workshop.value_axis': ('Value · currency / unit', 'Valeur · devise / unité'),
 'workshop.payout': ('Redemption · currency / unit', 'Remboursement · devise / unité'),
 'workshop.pnl': ('Expiry P&L · currency', 'P&L à l’échéance · devise'),
 'workshop.strategy': ('Strategy', 'Stratégie'),
 'workshop.units': ('Underlying units per leg', 'Unités de sous-jacent par jambe'),
 'workshop.strategy_units': ('Strikes and premiums are per unit. Outlay, P&L and Greeks include {units:g} underlying units per leg. No automatic ×100 contract multiplier is applied.', 'Strikes et primes sont par unité. Décaissement, P&L et sensibilités incluent {units:g} unités de sous-jacent par jambe. Aucun multiplicateur de contrat ×100 n’est appliqué.'),
 'workshop.model': ('Black–Scholes premiums', 'Primes Black–Scholes'),
 'workshop.manual': ('Enter premiums', 'Saisir les primes'),
 'workshop.premium_mode': ('Premium source', 'Source des primes'),
 'workshop.premium': ('First option premium / unit', 'Prime de la première option / unité'),
 'workshop.premium2': ('Second option premium / unit', 'Prime de la seconde option / unité'),
 'workshop.premium_help': ('Non-negative premium paid by the buyer per unit. The strategy applies the long/short sign. Leg order appears in the table below.', 'Prime positive payée par l’acheteur, par unité. La stratégie applique le signe achat/vente. L’ordre des jambes figure dans le tableau ci-dessous.'),
 'workshop.strategy_note': ('The solid curve is profit/loss at the common expiry, after the initial option premiums and stock purchase cost. Dashed curves are individual legs. It excludes financing, fees, margin, early exercise and dividends (q = 0). Changing volatility/time/rates changes model premiums; with entered premiums, it only changes the model Greeks. Maximum gain/loss considers every non-negative final price, even outside the chart.', 'La courbe pleine est le gain ou la perte à l’échéance commune, après primes initiales et coût d’achat des actions. Les pointillés détaillent chaque jambe. Financement, frais, marge, exercice anticipé et dividendes sont exclus (q = 0). Volatilité, temps et taux modifient les primes du modèle ; avec des primes saisies, seules les sensibilités du modèle changent. Le gain et la perte maximum couvrent tous les cours finaux positifs ou nuls, même hors graphique.'),
 'workshop.debit': ('Net initial outlay', 'Décaissement initial net'),
 'workshop.debit_help': ('Includes stock purchases and signed option premiums for the chosen units. Negative means cash received; short positions can still require collateral.', 'Inclut l’achat des actions et les primes signées pour le nombre d’unités choisi. Une valeur négative est un encaissement ; les positions vendeuses peuvent nécessiter du collatéral.'),
 'workshop.max_gain': ('Maximum gain', 'Gain maximum'),
 'workshop.max_loss': ('Maximum loss', 'Perte maximale'),
 'workshop.unlimited': ('Unlimited', 'Illimité'),
 'workshop.breakeven': ('Break-even final prices: {values}', 'Cours finaux d’équilibre : {values}'),
 'workshop.no_roots': ('none', 'aucun'),
 'workshop.zero_region': ('A whole price interval has zero P&L; listed break-even points include its boundaries.', 'Un intervalle entier de cours présente un P&L nul ; les points d’équilibre listés incluent ses bornes.'),
 'workshop.premium_warning': ('The entered premiums imply a gain or loss at every final price. Check price consistency, signs and units; this is not evidence of executable arbitrage.', 'Les primes saisies impliquent un gain ou une perte pour tous les cours finaux. Vérifiez la cohérence des prix, des signes et des unités ; cela ne prouve pas un arbitrage réalisable.'),
 'workshop.carry_notice': ('This example shows a positive or negative expiry P&L at every final price before financing. With non-zero rates, entry cash and expiry cash have different time values. This does not establish an arbitrage; borrowing costs or interest on cash are excluded.', 'Cet exemple présente un P&L positif ou négatif pour tous les cours finaux avant financement. Avec des taux non nuls, les montants initiaux et finaux n’ont pas la même valeur dans le temps. Cela ne démontre pas un arbitrage ; coût d’emprunt et intérêts sur la trésorerie sont exclus.'),
 'workshop.legs': ('What the strategy contains', 'Ce que contient la stratégie'),
 'workshop.instrument': ('Instrument', 'Instrument'),
 'workshop.signed_units': ('Signed units', 'Unités signées'),
 'workshop.leg_premium': ('Premium / unit', 'Prime / unité'),
 'workshop.stock': ('Underlying', 'Sous-jacent'),
 'workshop.greeks': ('Model sensitivities · entire strategy', 'Sensibilités du modèle · stratégie entière'),
 'workshop.greeks_note': ('Delta estimates the P&L for +1 in spot. Gamma measures how Delta changes. Vega is the P&L for +1 percentage point of annual volatility. These are local estimates today, not expiry outcomes; they include the selected units.', 'Delta estime le P&L pour +1 de cours. Gamma mesure la variation du Delta. Vega estime le P&L pour +1 point de pourcentage de volatilité annuelle. Ce sont des approximations locales aujourd’hui, pas des résultats à l’échéance ; elles incluent les unités choisies.'),
 'workshop.strike_order': ('Use K₂ > K for a call spread, strangle or collar; K₂ < K for a bear put spread.', 'Choisissez K₂ > K pour un call spread, un strangle ou un collar ; K₂ < K pour un bear put spread.'),
 'workshop.direction': ('Barrier direction', 'Sens de la barrière'),
 'workshop.down': ('Down · touched at or below H', 'Basse · touchée à H ou en dessous'),
 'workshop.up': ('Up · touched at or above H', 'Haute · touchée à H ou au-dessus'),
 'workshop.activation': ('Effect of a touch', 'Effet du franchissement'),
 'workshop.in': ('Knock-in · activates', 'Knock-in · active l’option'),
 'workshop.out': ('Knock-out · cancels', 'Knock-out · annule l’option'),
 'workshop.barrier': ('Barrier level · H', 'Niveau de barrière · H'),
 'workshop.touched': ('Barrier was already touched', 'La barrière a déjà été touchée'),
 'workshop.history': ('A past touch remains effective after a price recovery. Equality counts as a touch. Checking this switch tells the model about the contract’s past; no market history is downloaded.', 'Un franchissement passé reste effectif après un rebond. L’égalité compte comme un franchissement. Ce bouton renseigne le passé du contrat ; aucun historique de marché n’est téléchargé.'),
 'workshop.touch_probability': ('Touch probability · model', 'Probabilité de toucher · modèle'),
 'workshop.probability_help': ('Risk-neutral probability of touching at least once by expiry under constant volatility. Not a market forecast or the probability of losing money. 100% if already touched.', 'Probabilité risque-neutre de toucher au moins une fois avant l’échéance, à volatilité constante. Ni prévision de marché ni probabilité de perte. 100 % si la barrière est déjà touchée.'),
 'workshop.touched_info': ('Touch recorded: the knock-out is worth zero and the knock-in is the vanilla option. A recovery does not reset the contract.', 'Franchissement enregistré : le knock-out vaut zéro et le knock-in vaut l’option vanille. Un rebond ne remet pas le contrat à zéro.'),
 'workshop.barrier_note': ('A call pays max(Sₜ − K, 0); a put pays max(K − Sₜ, 0). A knock-in needs a barrier touch to activate that payoff; a knock-out loses it at the first touch. The model monitors continuously, allows exercise only at expiry, and pays no rebate after cancellation. Actual products may use different observation schedules.', 'Un call verse max(Sₜ − K, 0) ; un put verse max(K − Sₜ, 0). Le knock-in exige un franchissement pour activer ce paiement ; le knock-out le perd au premier franchissement. Le modèle observe la barrière en continu, n’autorise l’exercice qu’à l’échéance et ne verse aucune indemnité après annulation. Les produits réels peuvent avoir d’autres calendriers d’observation.'),
 'workshop.parity': ('In + out = vanilla: {ki:.4f} + {ko:.4f} = {vanilla:.4f}. Residual: {residual:.2e}. Same strike, expiry and barrier; zero rebate.', 'In + out = vanille : {ki:.4f} + {ko:.4f} = {vanilla:.4f}. Écart : {residual:.2e}. Même strike, échéance et barrière ; aucune indemnité.'),
 'workshop.curve': ('Reprice across today’s spot', 'Revaloriser selon le cours aujourd’hui'),
 'workshop.curve_note': ('Each point is a separate current-spot scenario with the entered past-touch status held fixed. This is not a simulated price path. Higher volatility can lower a knock-out price by increasing the chance of cancellation.', 'Chaque point est un scénario indépendant de cours actuel, en conservant le statut passé saisi. Ce n’est pas une trajectoire simulée. Une volatilité plus élevée peut réduire le prix d’un knock-out en augmentant le risque d’annulation.'),
 'workshop.discount': ('Discount certificate', 'Certificat Discount'),
 'workshop.bonus': ('Bonus certificate', 'Certificat Bonus'),
 'workshop.capped_bonus': ('Capped Bonus certificate', 'Certificat Bonus Cappé'),
 'workshop.certificate': ('Certificate', 'Certificat'),
 'workshop.level': ('Bonus level · B', 'Niveau Bonus · B'),
 'workshop.cap': ('Redemption cap · C', 'Plafond de remboursement · C'),
 'workshop.discount_note': ('At expiry you receive the lower of the underlying price and the cap. Selling a call finances the discount, but gives up upside above the cap. A discount is not capital protection: redemption can fall to zero.', 'À l’échéance, vous recevez le minimum entre le cours et le plafond. La vente d’un call finance la décote, en échange de l’abandon de la hausse au-dessus du plafond. Une décote n’est pas une protection du capital : le remboursement peut tomber à zéro.'),
 'workshop.bonus_note': ('If the lower barrier has never been touched, redemption is at least the Bonus level. Once touched, this floor disappears, even if the price recovers. The uncapped Bonus retains upside; Capped Bonus limits it to C. The entire price path matters, not just the final price.', 'Si la barrière basse n’a jamais été touchée, le remboursement atteint au moins le niveau Bonus. Dès qu’elle est touchée, ce plancher disparaît, même après un rebond. Le Bonus non cappé conserve la hausse ; le Bonus Cappé la limite à C. Toute la trajectoire compte, pas seulement le cours final.'),
 'workshop.replication': ('How the price is built', 'Comment le prix est construit'),
 'workshop.prepaid': ('Underlying delivered at expiry', 'Sous-jacent livré à l’échéance'),
 'workshop.bonus_put': ('+ Down-and-out put · strike B', '+ Put down-and-out · strike B'),
 'workshop.short_cap': ('− Call · strike C', '− Call · strike C'),
 'workshop.component': ('Component', 'Composant'),
 'workshop.replication_note': ('The underlying component costs S × exp(−qT): the holder receives no interim dividends. Add the conditional floor via a down-and-out put; subtract a call to cap the upside. The component values sum to the theoretical price. No issuer credit risk, fees, bid/ask or taxes are included.', 'La composante sous-jacent coûte S × exp(−qT) : le détenteur ne reçoit aucun dividende intermédiaire. Un put down-and-out ajoute le plancher conditionnel ; la vente d’un call plafonne la hausse. La somme des composants donne le prix théorique. Risque de crédit de l’émetteur, frais, fourchette achat/vente et fiscalité sont exclus.'),
 'workshop.never_hit': ('Barrier never touched', 'Barrière jamais touchée'),
 'workshop.hit': ('Barrier touched during life', 'Barrière touchée pendant la vie'),
 'workshop.redemption': ('Redemption at expiry', 'Remboursement à l’échéance'),
 'workshop.redemption_note': ('These curves show cash received, not profit: subtract your purchase price and financing costs to measure your outcome. The “never touched” curve only exists above H. Equal final prices can give different redemptions because of past touches.', 'Ces courbes montrent le montant reçu, pas le gain : déduisez votre prix d’achat et le financement pour mesurer votre résultat. La courbe « jamais touchée » n’existe qu’au-dessus de H. Un même cours final peut donner des remboursements différents selon les franchissements passés.'),
 'workshop.discount_redemption': ('This is cash received at expiry, not profit. The cap limits redemption; your purchase price and any financing costs still need to be deducted.', 'C’est le montant reçu à l’échéance, pas le gain. Le plafond limite le remboursement ; il faut encore déduire votre prix d’achat et les coûts de financement.'),
 'workshop.bonus_cost': ('With zero dividends, adding a Bonus floor to the underlying costs extra. The Bonus level is not a free yield or a guaranteed return on the purchase price.', 'Sans dividendes, ajouter un plancher Bonus au sous-jacent coûte plus cher. Le niveau Bonus n’est ni un rendement gratuit ni une performance garantie sur le prix d’achat.'),
 'workshop.bonus_touched': ('The barrier has been touched: the Bonus floor is gone. Only the underlying redemption remains, capped if applicable.', 'La barrière a été touchée : le plancher Bonus a disparu. Seul reste le remboursement lié au sous-jacent, avec plafond le cas échéant.'),
 'workshop.sources': ('Sources & calculation assumptions', 'Sources et hypothèses de calcul'),
 'workshop.sources_note': ('Product exploration inspired by [Derivatives Insights](https://derivativesinsights.com/). Original implementation; no data feed or affiliation. Barrier prices integrate the absorbing lognormal density under Black–Scholes–Merton. Continuous monitoring and in/out parity can also be checked in [QuantLib’s analytic engine](https://github.com/lballabio/QuantLib/blob/master/ql/pricingengines/barrier/analyticbarrierengine.cpp). Strategy definitions: [Options Industry Council](https://www.optionseducation.org/strategies/all-strategies-en). All parameters are illustrative or entered by you; there is no volatility-smile calibration.', 'Exploration des produits inspirée de [Derivatives Insights](https://derivativesinsights.com/). Implémentation originale ; aucun flux de données ni affiliation. Les barrières sont valorisées par intégration de la densité lognormale absorbante sous Black–Scholes–Merton. Observation continue et parité in/out sont également vérifiables dans [le moteur analytique QuantLib](https://github.com/lballabio/QuantLib/blob/master/ql/pricingengines/barrier/analyticbarrierengine.cpp). Définition des stratégies : [Options Industry Council](https://www.optionseducation.org/strategies/all-strategies-en). Les paramètres sont illustratifs ou saisis ; aucune calibration de smile de volatilité.'),
 'workshop.finite': ('Enter finite numbers in every field.', 'Saisissez des nombres finis dans tous les champs.'),
 'workshop.positive': ('Prices must be positive; time and volatility cannot be negative.', 'Les prix doivent être positifs ; temps et volatilité ne peuvent pas être négatifs.'),
 'workshop.variant': ('Unknown product variant.', 'Variante de produit inconnue.'),
 'workshop.premium_count': ('Enter one premium for each option leg.', 'Saisissez une prime par jambe optionnelle.'),
 'workshop.range': ('These parameters exceed the numerical calculation range.', 'Ces paramètres dépassent le domaine de calcul numérique.'),
 'workshop.numerical': ('The model could not produce a reliable value for these parameters.', 'Le modèle ne peut pas fournir une valeur fiable avec ces paramètres.'),
 'workshop.barrier_below_bonus': ('The barrier must be strictly below the Bonus level.', 'La barrière doit être strictement sous le niveau Bonus.'),
 'workshop.cap_above_bonus': ('The cap must be at or above the Bonus level.', 'Le plafond doit être supérieur ou égal au niveau Bonus.'),
}

_STRATEGIES = {
 'Long Call': ('Long call', 'Achat de call'),
 'Long Put': ('Long put', 'Achat de put'),
 'Short Call': ('Short call', 'Vente de call'),
 'Short Put': ('Short put', 'Vente de put'),
 'Bull Call Spread': ('Bull call spread', 'Call spread haussier'),
 'Bear Put Spread': ('Bear put spread', 'Put spread baissier'),
 'Long Straddle': ('Long straddle', 'Achat de straddle'),
 'Long Strangle': ('Long strangle', 'Achat de strangle'),
 'Covered Call': ('Covered call', 'Call couvert'),
 'Protective Put': ('Protective put', 'Put de protection'),
 'Collar': ('Collar', 'Collar'),
}
WORKSHOP.update({'workshop.strategy.' + name: pair for name, pair in _STRATEGIES.items()})

_VIEWS = {
 'Long Call': ('Pay a premium to benefit from a rise. Loss is limited to the premium; upside is uncapped.', 'Payer une prime pour profiter d’une hausse. La perte est limitée à la prime ; la hausse n’est pas plafonnée.'),
 'Long Put': ('Pay for a fall in price, or to hedge an exposure held elsewhere. The premium can be lost entirely.', 'Payer pour profiter d’une baisse ou couvrir une exposition détenue ailleurs. La prime peut être perdue en totalité.'),
 'Short Call': ('Receive a premium but owe the upside above the strike. Without underlying cover, loss is unlimited.', 'Encaisser une prime mais devoir payer la hausse au-dessus du strike. Sans couverture par le sous-jacent, la perte est illimitée.'),
 'Short Put': ('Receive a premium in exchange for bearing a fall below the strike. Large losses remain possible if the underlying falls towards zero.', 'Encaisser une prime en échange du risque de baisse sous le strike. La perte peut être élevée si le sous-jacent tend vers zéro.'),
 'Bull Call Spread': ('Buy the lower-strike call and sell the higher-strike call. This reduces entry cost but caps the benefit of a rise.', 'Acheter le call au strike bas et vendre celui au strike haut. Le coût baisse, mais le gain en cas de hausse est plafonné.'),
 'Bear Put Spread': ('Buy the higher-strike put and sell the lower-strike put. This expresses a fall with a capped gain and defined cost.', 'Acheter le put au strike haut et vendre celui au strike bas. La stratégie vise une baisse avec un gain plafonné et un coût défini.'),
 'Long Straddle': ('Buy a call and a put at the same strike. A move in either direction must be large enough to cover both premiums.', 'Acheter un call et un put au même strike. Le mouvement, dans un sens ou l’autre, doit couvrir les deux primes.'),
 'Long Strangle': ('Buy a lower-strike put and a higher-strike call. A large move is needed; between the strikes, both premiums are lost at expiry.', 'Acheter un put au strike bas et un call au strike haut. Il faut un mouvement important ; entre les strikes, les deux primes sont perdues à l’échéance.'),
 'Covered Call': ('Own the underlying and sell a call. Premium income cushions a small fall, but does not protect against a large one; upside is capped.', 'Détenir le sous-jacent et vendre un call. La prime amortit une petite baisse, sans protéger d’une forte chute ; la hausse est plafonnée.'),
 'Protective Put': ('Own the underlying and buy a put. The put sets a floor at expiry, at the cost of its premium.', 'Détenir le sous-jacent et acheter un put. Le put fixe un plancher à l’échéance, en contrepartie de sa prime.'),
 'Collar': ('Own the underlying, buy a lower-strike put and sell a higher-strike call. Selling the upside helps pay for downside protection.', 'Détenir le sous-jacent, acheter un put au strike bas et vendre un call au strike haut. La vente de la hausse contribue au financement de la protection.'),
}
WORKSHOP.update({'workshop.view.' + name: pair for name, pair in _VIEWS.items()})
WORKSHOP.update({
 'help.workshop.price': ('Theoretical present value per unit from the entered parameters. A model value is not an executable market quote.', 'Valeur théorique actuelle par unité issue des paramètres saisis. Ce n’est pas une cotation de marché exécutable.'),
 'help.workshop.vanilla_value': ('The same call or put with no barrier, using the same strike, time, volatility, rate and dividends.', 'Même call ou put sans barrière, avec les mêmes strike, durée, volatilité, taux et dividendes.'),
 'help.workshop.debit': WORKSHOP['workshop.debit_help'],
 'help.workshop.touch_probability': WORKSHOP['workshop.probability_help'],
 'help.workshop.max_gain': ('Largest positive expiry P&L across all non-negative final underlying prices. Excludes funding, dividends and fees.', 'Plus grand P&L positif à l’échéance sur tous les cours finaux positifs ou nuls. Hors financement, dividendes et frais.'),
 'help.workshop.max_loss': ('Magnitude of the largest negative expiry P&L, across all non-negative final prices. Excludes margin calls and losses from closing early.', 'Montant de la plus forte perte à l’échéance sur tous les cours finaux positifs ou nuls. Exclut les appels de marge et les pertes de clôture anticipée.'),
})
