import pandas as pd
import plotly.express as px
import streamlit as st

from app_pages.common import render_module_header
from engines.cross_asset_dashboard_engine import (
    CrossAssetRiskInputs,
    build_default_cross_asset_inputs,
    build_risk_heatmap_table,
    calculate_cross_asset_stress_table,
    calculate_cross_asset_summary,
    cross_asset_summary_to_dict,
    generate_cross_asset_commentary,
)


def _format_percent(value: float) -> str:
    return f"{value:.2%}"


def _format_score(value: float) -> str:
    return f"{value:.1f}/100"


def _format_amount(value: float) -> str:
    return f"{value:,.0f}"


def render() -> None:
    render_module_header(
        title="Cross-Asset Dashboard",
        caption="Manager view: rates, financing, structured products, and portfolio risk synthesis.",
        objective=(
            "Objective: aggregate the main risk signals from the terminal into a cross-asset overview "
            "for desk discussion, risk monitoring, and scenario comparison."
        ),
    )

    default_inputs = build_default_cross_asset_inputs()

    st.subheader("Cross-Asset Risk Inputs")

    st.caption(
        "Inputs are proxy dashboard values. They summarize the key outputs generated by the individual modules."
    )

    c1, c2, c3, c4 = st.columns(4)

    with c1:
        total_dv01 = st.number_input(
            "Total DV01",
            min_value=0.0,
            value=float(default_inputs.total_dv01),
            step=1_000.0,
        )
        long_end_dv01_share = st.slider(
            "Long-end DV01 share",
            min_value=0.0,
            max_value=1.0,
            value=float(default_inputs.long_end_dv01_share),
            step=0.01,
        )

    with c2:
        repo_margin_deficit = st.number_input(
            "Repo margin deficit",
            min_value=0.0,
            value=float(default_inputs.repo_margin_deficit),
            step=25_000.0,
        )
        collateral_market_value = st.number_input(
            "Collateral market value",
            min_value=1.0,
            value=float(default_inputs.collateral_market_value),
            step=500_000.0,
        )

    with c3:
        structured_autocall_probability = st.slider(
            "Autocall probability",
            min_value=0.0,
            max_value=1.0,
            value=float(default_inputs.structured_autocall_probability),
            step=0.01,
        )
        structured_barrier_breach_probability = st.slider(
            "Barrier breach probability",
            min_value=0.0,
            max_value=1.0,
            value=float(default_inputs.structured_barrier_breach_probability),
            step=0.01,
        )

    with c4:
        portfolio_var_95 = st.slider(
            "Portfolio VaR 95%",
            min_value=0.0,
            max_value=0.10,
            value=float(default_inputs.portfolio_var_95),
            step=0.001,
        )
        portfolio_cvar_95 = st.slider(
            "Portfolio CVaR 95%",
            min_value=0.0,
            max_value=0.15,
            value=float(default_inputs.portfolio_cvar_95),
            step=0.001,
        )
        max_drawdown = st.slider(
            "Max drawdown",
            min_value=-0.80,
            max_value=0.0,
            value=float(default_inputs.max_drawdown),
            step=0.01,
        )

    st.subheader("Portfolio Exposure Mix")

    e1, e2, e3, e4 = st.columns(4)

    with e1:
        equity_weight = st.slider("Equity weight", 0.0, 1.0, float(default_inputs.equity_weight), 0.01)

    with e2:
        credit_weight = st.slider("Credit weight", 0.0, 1.0, float(default_inputs.credit_weight), 0.01)

    with e3:
        rates_weight = st.slider("Rates weight", 0.0, 1.0, float(default_inputs.rates_weight), 0.01)

    with e4:
        alternatives_weight = st.slider("Alternatives weight", 0.0, 1.0, float(default_inputs.alternatives_weight), 0.01)

    exposure_sum = equity_weight + credit_weight + rates_weight + alternatives_weight

    if exposure_sum <= 0:
        st.error("Exposure weights must sum to a positive number.")
        return

    inputs = CrossAssetRiskInputs(
        total_dv01=float(total_dv01),
        long_end_dv01_share=float(long_end_dv01_share),
        repo_margin_deficit=float(repo_margin_deficit),
        collateral_market_value=float(collateral_market_value),
        structured_autocall_probability=float(structured_autocall_probability),
        structured_barrier_breach_probability=float(structured_barrier_breach_probability),
        portfolio_var_95=float(portfolio_var_95),
        portfolio_cvar_95=float(portfolio_cvar_95),
        max_drawdown=float(max_drawdown),
        equity_weight=float(equity_weight / exposure_sum),
        credit_weight=float(credit_weight / exposure_sum),
        rates_weight=float(rates_weight / exposure_sum),
        alternatives_weight=float(alternatives_weight / exposure_sum),
    )

    summary = calculate_cross_asset_summary(inputs)
    summary_dict = cross_asset_summary_to_dict(summary)
    heatmap_df = build_risk_heatmap_table(summary)
    stress_df = calculate_cross_asset_stress_table(inputs)
    commentary = generate_cross_asset_commentary(inputs, summary, stress_df)

    st.subheader("Cross-Asset Risk Summary")

    k1, k2, k3, k4, k5 = st.columns(5)

    k1.metric("Composite Risk", summary.composite_risk_label)
    k2.metric("Composite Score", _format_score(summary.composite_score))
    k3.metric("Dominant Bucket", summary.dominant_risk_bucket)
    k4.metric("Worst Stress", stress_df.loc[stress_df["total_proxy_impact_pct"].idxmin(), "scenario"])
    k5.metric("Worst Stress Impact", _format_percent(stress_df["total_proxy_impact_pct"].min()))

    s1, s2, s3, s4 = st.columns(4)

    s1.metric("Rates Score", _format_score(summary.rates_score))
    s2.metric("Financing Score", _format_score(summary.financing_score))
    s3.metric("Structured Score", _format_score(summary.structured_products_score))
    s4.metric("Portfolio Score", _format_score(summary.portfolio_score))

    st.subheader("Desk Commentary")

    with st.container(border=True):
        for comment in commentary:
            st.markdown(f"- {comment}")

    st.subheader("Risk Heatmap")

    heatmap_matrix = heatmap_df.set_index("risk_bucket")[["risk_score"]]

    fig_heatmap = px.imshow(
        heatmap_matrix,
        text_auto=".1f",
        title="Cross-Asset Risk Heatmap",
        aspect="auto",
        labels={"color": "Risk score"},
    )
    st.plotly_chart(fig_heatmap, width="stretch")

    st.dataframe(
        heatmap_df.style.format({"risk_score": "{:.1f}"}),
        width="stretch",
    )

    fig_scores = px.bar(
        heatmap_df,
        x="risk_bucket",
        y="risk_score",
        color="risk_label",
        title="Risk Score by Bucket",
        labels={"risk_bucket": "Risk Bucket", "risk_score": "Risk Score"},
    )
    st.plotly_chart(fig_scores, width="stretch")

    st.subheader("Cross-Asset Stress Scenarios")

    st.dataframe(
        stress_df.style.format(
            {
                "rates_impact_amount": "{:,.0f}",
                "financing_impact_amount": "{:,.0f}",
                "structured_products_impact_pct": "{:.2%}",
                "portfolio_impact_pct": "{:.2%}",
                "total_proxy_impact_pct": "{:.2%}",
            }
        ),
        width="stretch",
    )

    fig_stress = px.bar(
        stress_df,
        x="scenario",
        y="total_proxy_impact_pct",
        title="Total Proxy Impact by Cross-Asset Stress Scenario",
        labels={"scenario": "Scenario", "total_proxy_impact_pct": "Total Proxy Impact"},
    )
    st.plotly_chart(fig_stress, width="stretch")

    st.subheader("Dashboard Inputs Snapshot")

    input_snapshot_df = pd.DataFrame(
        [{"metric": key, "value": value} for key, value in summary_dict.items()]
    )
    input_snapshot_df["value"] = input_snapshot_df["value"].astype(str)

    st.dataframe(input_snapshot_df, width="stretch")

    st.subheader("Methodology Notes")

    st.markdown(
        """
        - Rates risk score combines total DV01 and long-end DV01 concentration.
        - Financing risk score is driven by repo margin deficit as a share of collateral value.
        - Structured products score rises with barrier breach probability and falls with autocall probability.
        - Portfolio risk score combines historical VaR, CVaR, and max drawdown.
        - Composite risk score is a weighted average of rates, financing, structured products, and portfolio risk scores.
        - Cross-asset stress scenarios are simplified proxy shocks, not calibrated risk scenarios.
        - This dashboard is designed for synthesis and discussion, not production risk aggregation.
        """
    )
